import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

// Singleton-style collection, same pattern as EmailSettings: exactly one
// document holds the business's own details, used to brand invoices, email
// templates, and any other customer-facing document generated by the app.
@Schema({ timestamps: true })
export class BusinessInfo extends Document {
  @Prop()
  name?: string;

  @Prop()
  address?: string;

  @Prop()
  town?: string;

  @Prop()
  postcode?: string;

  @Prop()
  telephone?: string;

  @Prop()
  email?: string;

  @Prop()
  website?: string;

  // Base64 data URI, same storage approach as Customer.agreement.signatureImage --
  // no filesystem/blob storage needed, and it survives fine on Render's ephemeral
  // filesystem since it lives in Mongo like everything else.
  @Prop()
  logoImage?: string;

  // termsHtml is what's actually rendered (Business Info preview, the public
  // intake form, the customer PDF export); termsDocx is the original upload,
  // kept only so staff can download back the exact file they gave us -- it's
  // never re-parsed. termsFileName is display-only.
  @Prop()
  termsHtml?: string;

  // Base64 data URI, same storage approach as logoImage above.
  @Prop()
  termsDocx?: string;

  @Prop()
  termsFileName?: string;

  // Shown to customers on invoices so they know where to send payment --
  // not secret (it's meant to be disclosed), so no encryption, same as the
  // rest of the business's contact details above.
  @Prop()
  bankName?: string;

  @Prop()
  sortCode?: string;

  @Prop()
  accountNumber?: string;

  // Numbering for generated invoices/quotes -- {year} and {seq} are
  // substituted by formatDocumentNumber (backend/src/common/document-number.util.ts);
  // *NextNumber is the number the *next* created document will use, and is
  // incremented atomically each time InvoicesService/QuotesService issues one.
  // Both are staff-editable so numbering can be renamed or fast-forwarded
  // (e.g. after deleting documents, or to match an existing paper sequence).
  @Prop({ default: 'INV-{year}-{seq}' })
  invoiceNumberTemplate?: string;

  @Prop({ default: 1 })
  invoiceNextNumber?: number;

  @Prop({ default: 'QUO-{year}-{seq}' })
  quoteNumberTemplate?: string;

  @Prop({ default: 1 })
  quoteNextNumber?: number;

  @Prop({ default: 'PAY-{year}-{seq}' })
  paymentNumberTemplate?: string;

  @Prop({ default: 1 })
  paymentNextNumber?: number;
}

export const BusinessInfoSchema = SchemaFactory.createForClass(BusinessInfo);
